name: NUnit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./mcv-comment

    env:
      configuration_name: Release

    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Download
        run: |
          Invoke-WebRequest https://int-main.net/app/MultiCommentViewer_v0.6.1_beta.zip -OutFile mcv.zip

      - name: Extract
        run: |
          Expand-Archive -Path ./mcv.zip -DestinationPath ./lib/mcv
          rm ./mcv.zip

      - name: Build
        run: |
          dotnet restore
          msbuild -p:Configuration=${env:configuration_name}

      - name: Test
        run: dotnet test -c ${env:configuration_name}
